name: CD
on:
    push:
    pull_request:
    workflow_dispatch:
    workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT:       /home/runner/work/caravel_mpw/openlane
      PDK_ROOT:            /home/runner/work/caravel_mpw/pdks
      CARAVEL_ROOT:        /home/runner/work/caravel_mpw/caravel_mpw/caravel-lite
      OPENLANE_IMAGE_NAME: efabless/openlane:2021.11.25_01.26.14
    steps:
       - uses: actions/checkout@v2
       - name: debug
         run:  |
           echo ${{ github.event_name }}
       - name: Install Magic
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_magic.sh
       - name: Build PDK
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/build_pdk.sh
       - name: Install MCW
         run: make install_mcw MCW=PICO
       - name: uncompress
         run: make uncompress
       - name: build user gds
         run: |
           bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh
       - name: build wrapper gds
         run: |
           bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh
       - name: compress
         run:  |
           make uninstall
           make uninstall_mcw
           make compress
       - name: push
         #if: github.event_name == 'workflow_dispatch'
         run: |
           ls -la
           git status
           git add def gds lef mag maglef signoff verilog spi
           git status
           git config user.email "rbacik@hotmail.com"
           git config user.name "roman3017"
           git commit -m "action: update build"
           git push origin HEAD:main
