name: CI
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CD"]
    types:
       - completed
jobs:
  precheck:
    timeout-minutes: 720
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install Magic
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_magic.sh
      - name: Build PDK
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/build_pdk.sh
      - name: Install The Precheck
        run: git clone --depth=1 https://github.com/efabless/mpw_precheck.git ${GITHUB_WORKSPACE}/mpw_precheck
      - name: Run The Precheck
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/run_precheck.sh
  dv_rtl:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env: 
      OPENLANE_ROOT:       /home/runner/work/caravel_mpw/openlane
      PDK_ROOT:            /home/runner/work/caravel_mpw/pdks
      CARAVEL_ROOT:        /home/runner/work/caravel_mpw/caravel_mpw/caravel-lite
    steps:
       - uses: actions/checkout@v2
       - name: Install Magic
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_magic.sh
       - name: Build PDK
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/build_pdk.sh
       - name: Install MCW
         run: make install_mcw MCW=PICO
       - name: Run DV tests
         # Run test number 0,1,2,3,4 in one job       <test-ids>   <sim-mode>
         run: bash .github/scripts/dv/run-dv-tests.sh 4            RTL
  dv_gl:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env: 
      OPENLANE_ROOT:       /home/runner/work/caravel_mpw/openlane
      PDK_ROOT:            /home/runner/work/caravel_mpw/pdks
      CARAVEL_ROOT:        /home/runner/work/caravel_mpw/caravel_mpw/caravel-lite
    steps:
       - uses: actions/checkout@v2
       - name: Install Magic
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/install_magic.sh
       - name: Build PDK
         run: bash ${GITHUB_WORKSPACE}/.github/scripts/build_pdk.sh
       - name: Install MCW
         run: make install_mcw MCW=PICO
       - name: Run DV tests
         # Run test number 0,1,2,3,4 in one job       <test-ids>   <sim-mode>
         run: bash .github/scripts/dv/run-dv-tests.sh 4            GL
  tag_repo:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          tag: ${{ steps.date.outputs.date }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
